[aws]
disabled = true

[character]
style_success = "purple"

[cmd_duration]
min_time = 5_000
prefix = ""

[directory]
truncation_length = 8
truncate_to_repo = false
prefix = ""
style = "blue"

[git_branch]
symbol = ""
prefix = ""
style = "bright-black"

[git_commit]
style = "bright-black"

[git_state]
disabled = true

[git_status]
stashed = ""
diverged = ""
show_sync_count = true
style = "dimmed"

[jobs]
threshold = 0
style = "yellow"

[nodejs]
style = "green"
