export DOTFILES_DIR="$HOME/.dotfiles"
export NVM_LAZY_LOAD=true
export HISTCONTROL=ignorespace

bindkey -v
bindkey "jj" vi-cmd-mode
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

zstyle ":completion:*" matcher-list "m:{a-z}={A-Z}"
autoload -U compinit && compinit

source <(antibody init)

antibody bundle lukechilds/zsh-nvm
antibody bundle mafredri/zsh-async
antibody bundle sindresorhus/pure
antibody bundle zsh-users/zsh-completions
antibody bundle zsh-users/zsh-syntax-highlighting

source $DOTFILES_DIR/plugins/aliases.zsh
source $DOTFILES_DIR/plugins/directories.zsh
source $DOTFILES_DIR/plugins/history.zsh
source $DOTFILES_DIR/plugins/prompt.zsh
source $DOTFILES_DIR/ubuntu/fzf.zsh

typeset -U PATH
