#!/usr/bin/env zsh

###
# PRE-PUSH HOOK
###
unsetopt nomatch

## Coffeescript Lint
COFFEELINT="coffeelint"
COFFEELINT_CONFIG="~/.coffeelint.json"

if ! type "$COFFEELINT" > /dev/null; then
    echo "[INFO] Coffeelint not found."
else
    if ls **/*.coffee 1> /dev/null 2>&1; then
        echo "Linting Coffee files..."
        if [ -f "$COFFEELINT_CONFIG" ]; then
            $COFFEELINT -f $COFFEELINT_CONFIG **/*.coffee
        else
            $COFFEELINT $COFFEE_FILES **/*.coffee
        fi
    fi
fi

## Exit
if [ $? = 1 ]; then
    echo "Pre-push tests failed. Aborting commit"
    exit 1
else
    exit 0
fi
